id = "fsharp"
name = "F#"
description = "F# language support for Zed"
version = "0.0.9"
schema_version = 1
authors = ["Nathan Collins <me@nathancollins.dev>"]
repository = "https://github.com/nathanjcollins/zed-fsharp"

[settings]
fsac_custom_path = { type = "string", optional = true, description = "Custom path to fsautocomplete binary" }
fsac_custom_arguments = { type = "array", items = "string", default = [], description = "Additional arguments for fsautocomplete" }

[language_servers.fsautocomplete]
name = "fsautocomplete"
language = "FSharp"

[grammars.fsharp]
repository = "https://github.com/ionide/tree-sitter-fsharp"
commit = "c4347939b4fb439771dc2561a6923fba6a78251b"

[[capabilities]]
kind = "process:exec"
command = "dotnet"
args = ["*"]
